DESCRIBE ALUNO
-- DESCRIBE OU DESC USADOS PARA VER O QUE TEM DENTRO DAS TABELAS
DESC PROFESSOR 

-- O COMANDO SELECT SERVE PARA CONSULTAR OS DADOS
SELECT * FROM ALUNO;

SELECT SEXO,CIDADE,NOME FROM ALUNO


-- ALIAS PARA SIMPLIFICAR O NOME DA TABELA
-- mais de uma palavra uma aspas dupla
SELECT NOME "Nome completo",
MATRICULA AS mat, 
DATANASCIMENTO  AS nascimento,
SEXO FROM ALUNO

DESCRIBE ALUNO


-- comando select 
-- somar também é só acrescentar + 
SELECT matricula AS mat,
codTurma "codigo da turma",
nota+0.5 "nota com acrescimo",
nota "nota anterior"
FROM FREQUENTA

-- DISTINCT USADO PARA EVITAR OPERADORES DUPLICADOS
-- SEMPRE VEM RESULTADOS COM VALORES DIFERENTES 

SELECT DISTINCT nome,sexo FROM ALUNO
SELECT DISTINCT bairro FROM ALUNO

-- CONCATENAÇÃO JUNTAR COLUNAS STRING NA QUERY 
-- '' as aspas servem para dar espaço e deixar mais bonito aqui
SELECT nome, 
cidade || ' ' ||
bairro || ' ' ||
cep || ' ' ||
endereco  "Endereço completo" 
FROM ALUNO


-- expressões aritméticas 
-- pode trabalhar com número multiplicando, dividindo etc 
SELECT 
matricula,
nota "nota antiga",
nota+0.5 "nova nota"
FROM FREQUENTA

DESCRIBE FREQUENTA


-- VALOR NULL = VALOR NULO AUSÊNCIA DE VALOR

INSERT INTO ALUNO 
VALUES ('UC120052210', 'Julia Renata', 'F', '478721716', 11247132, '12/09/2006', NULL, NULL, NULL, NULL);
INSERT INTO ALUNO
VALUES ('UC124052210', 'Marcone Freitas', 'M', '47872sa1716', 1124711232, '12/1/2006', NULL, NULL, NULL, NULL);


SELECT * FROM ALUNO 
SELECT nome,
cidade || '--Cidade--'
FROM ALUNO

INSERT INTO 
FREQUENTA VALUES ('UC12010521', 'T01', 7.0,0,1,2012);



-- WHERE SERVE PARA LIMITAR AS CONSULTAS
SELECT * FROM ALUNO 
WHERE sexo = 'F'
-- EXEMPLO

SELECT * FROM FREQUENTA
WHERE NOTA >= 8.0 

-- != OPERADOR DIFERENTE 
SELECT * FROM FREQUENTA
WHERE NOTA != 8.0

-- BETWEEN COMPARAR VALOR DE UMA COLUNA EM UMA FAIXA DE VALORES

SELECT * FROM FREQUENTA
WHERE NOTA BETWEEN 7.0 AND 10.0

-- IN É USADO PARA LIMITAR 

SELECT * FROM FREQUENTA 
WHERE NOTA IN (7,8)

-- OR FUNCIONA QUASE IGUAL
SELECT * FROM FREQUENTA
WHERE NOTA = 7.0 OR NOTA = 8.0
-- % REPRESENTA ZERO OU MAIS CARACTERES
-- O _ REPRESENTA EXATAMENTE UM CARACTER


-- VAI TRAZER TODOS OS ALUNOS QUE COMEÇAM COM A LETRA A
SELECT * FROM ALUNO
WHERE NOME LIKE 'A%'

SELECT * FROM ALUNO
WHERE NOME LIKE '____SAMPAIO'
 

-- VALORES NULOS

SELECT * FROM ALUNO
WHERE cidade IS NULL

-- para comparar colunas que não estão nulos
SELECT * FROM ALUNO
WHERE cidade IS not NULL

-- quando precisa ser verdadeiro uso o and
SELEC T * FROM ALUNO
WHERE sexo = 'M' AND bairro = 'Aguas Clares'

-- ORDER BY PARA ORDENAR OS RESULTADOS
-- ASC ORDEM CRESCENTE 
-- DESC ORDEM DECRESCENTE
SELECT * FROM ALUNO
ORDER BY NOME ASC 
-- VAO PRDERNAR OS NOMES EM CRESCENTE 

SELECT * FROM ALUNO
ORDER BY bairro -- mesmo sem usar asc vai em ordem crescente

SELECT * FROM FREQUENTA
ORDER BY nota DESC

SELECT * FROM ALUNO
ORDER BY nome, bairro 


-- max serve para trazer o maior valor de uma coluna
SELECT MAX(nota) FROM FREQUENTA
SELECT MAX(datanascimento) FROM ALUNO
SELECT MAX(nome) FROM ALUNO
ORDER BY nome 

-- MIN SERVE PARA TRAZER O MENOR VALOR DE UMA COLUNA
SELECT MIN(nota) FROM FREQUENTA
-- DA PARA USAR MIN E MAX JUNTOS
SELECT MIN(nota), MAX(nota) FROM FREQUENTA
SELECT MIN(datanascimento) FROM ALUNO

-- COUNT CONTA A QUANTIDADE DE DETERMINADA COISA
SELECT COUNT(*) FROM ALUNO
SELECT COUNT(endereco) FROM ALUNO

-- FUNCAO AVG PARA CALCULAR A MEDIA DE UMA COLUNA
SELECT AVG(nota) FROM FREQUENTA
-- AVG APENAS PARA VALORES NÚMERICOS
SELECT AVG(falta) FROM FREQUENTA

-- SUM SERVE PARA CALCULAR A SOMA DE UMA COLUNA
SELECT SUM(nota) FROM FREQUENTA
-- APENAS PARA VALORES NUMÉRICOS

